import sys
import os
from pathlib import Path
from datetime import datetime

sys.path.append(str(Path(__file__).resolve().parents[2]))
from config import OUTPUT_DIR

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer,
        Table, TableStyle, HRFlowable
    )
    from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False
    print("⚠️  reportlab not installed — pip install reportlab")


def generate_memo_pdf(memo_data: dict) -> str:
    """
    Generates a professional PDF investment memo.

    Args:
        memo_data: dict with ticker, company_name, recommendation,
                   confidence_score, summary, bull_case, bear_case,
                   metrics, flagged_claims, sources

    Returns:
        Path to the generated PDF file
    """
    if not REPORTLAB_AVAILABLE:
        raise ImportError("reportlab is required — pip install reportlab")

    ticker = memo_data.get("ticker", "UNKNOWN").upper()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{ticker}_investment_memo_{timestamp}.pdf"
    filepath = OUTPUT_DIR / filename

    # ── Document setup ────────────────────────────────────────────────────────
    doc = SimpleDocTemplate(
        str(filepath),
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch
    )

    # ── Styles ────────────────────────────────────────────────────────────────
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        fontSize=20,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=4,
        alignment=TA_LEFT
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#666666"),
        spaceAfter=2
    )
    section_style = ParagraphStyle(
        "Section",
        parent=styles["Heading2"],
        fontSize=13,
        textColor=colors.HexColor("#1a1a2e"),
        spaceBefore=14,
        spaceAfter=4,
        borderPad=2
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#333333"),
        spaceAfter=4
    )
    small_style = ParagraphStyle(
        "Small",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.HexColor("#888888")
    )

    # ── Color for recommendation ──────────────────────────────────────────────
    rec = memo_data.get("recommendation", "HOLD")
    rec_colors = {
        "BUY": colors.HexColor("#27ae60"),
        "HOLD": colors.HexColor("#f39c12"),
        "SELL": colors.HexColor("#e74c3c"),
        "INSUFFICIENT_DATA": colors.HexColor("#95a5a6")
    }
    rec_color = rec_colors.get(rec, colors.HexColor("#95a5a6"))

    rec_style = ParagraphStyle(
        "Rec",
        parent=styles["Normal"],
        fontSize=16,
        textColor=rec_color,
        fontName="Helvetica-Bold"
    )

    # ── Build content ─────────────────────────────────────────────────────────
    content = []

    # Header
    company = memo_data.get("company_name", ticker)
    content.append(Paragraph(f"{company} ({ticker})", title_style))
    content.append(Paragraph("Investment Research Memo", subtitle_style))
    content.append(Paragraph(
        f"Generated by FinSight AI · {datetime.now().strftime('%B %d, %Y')}",
        subtitle_style
    ))
    content.append(HRFlowable(width="100%", thickness=2,
                               color=colors.HexColor("#1a1a2e")))
    content.append(Spacer(1, 8))

    # Recommendation + confidence
    confidence = memo_data.get("confidence_score", 0)
    content.append(Paragraph(
        f"Recommendation: <b>{rec}</b>  |  "
        f"Confidence Score: <b>{confidence:.0%}</b>  |  "
        f"Flagged Claims: <b>{len(memo_data.get('flagged_claims', []))}</b>",
        body_style
    ))
    content.append(Spacer(1, 8))

    # Summary
    content.append(Paragraph("Executive Summary", section_style))
    content.append(HRFlowable(width="100%", thickness=0.5,
                               color=colors.HexColor("#cccccc")))
    content.append(Spacer(1, 4))
    summary = memo_data.get("summary", "No summary available.")
    for part in summary.split(" | "):
        if part.strip():
            content.append(Paragraph(part.strip(), body_style))
    content.append(Spacer(1, 6))

    # Key Metrics table
    metrics = memo_data.get("metrics", {})
    metric_rows = [
        ["Metric", "Value"],
        ["Revenue", metrics.get("revenue") or "N/A"],
        ["Revenue Growth YoY", metrics.get("revenue_growth_yoy") or "N/A"],
        ["EPS", metrics.get("eps") or "N/A"],
        ["EPS Growth YoY", metrics.get("eps_growth_yoy") or "N/A"],
        ["Gross Margin", metrics.get("gross_margin") or "N/A"],
        ["Operating Margin", metrics.get("operating_margin") or "N/A"],
        ["Free Cash Flow", metrics.get("free_cash_flow") or "N/A"],
        ["Forward Guidance", metrics.get("guidance") or "N/A"],
    ]
    # Remove N/A rows except first 4
    filtered_rows = [metric_rows[0]] + [
        r for r in metric_rows[1:] if r[1] != "N/A"
    ]
    if len(filtered_rows) < 3:
        filtered_rows = metric_rows[:6]

    content.append(Paragraph("Key Financial Metrics", section_style))
    content.append(HRFlowable(width="100%", thickness=0.5,
                               color=colors.HexColor("#cccccc")))
    content.append(Spacer(1, 4))

    table = Table(filtered_rows, colWidths=[2.5 * inch, 4.5 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
         [colors.HexColor("#f8f9fa"), colors.white]),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
        ("PADDING", (0, 0), (-1, -1), 6),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    content.append(table)
    content.append(Spacer(1, 6))

    # Bull Case
    content.append(Paragraph("Bull Case", section_style))
    content.append(HRFlowable(width="100%", thickness=0.5,
                               color=colors.HexColor("#27ae60")))
    content.append(Spacer(1, 4))
    bull = memo_data.get("bull_case", "")
    for i, point in enumerate(bull.split(" | "), 1):
        if point.strip():
            content.append(Paragraph(f"{i}. {point.strip()}", body_style))
    content.append(Spacer(1, 6))

    # Bear Case
    content.append(Paragraph("Bear Case", section_style))
    content.append(HRFlowable(width="100%", thickness=0.5,
                               color=colors.HexColor("#e74c3c")))
    content.append(Spacer(1, 4))
    bear = memo_data.get("bear_case", "")
    for i, point in enumerate(bear.split(" | "), 1):
        if point.strip():
            content.append(Paragraph(f"{i}. {point.strip()}", body_style))
    content.append(Spacer(1, 6))

    # Flagged Claims
    flagged = memo_data.get("flagged_claims", [])
    if flagged:
        content.append(Paragraph("⚠️ Flagged Claims", section_style))
        content.append(HRFlowable(width="100%", thickness=0.5,
                                   color=colors.HexColor("#f39c12")))
        content.append(Spacer(1, 4))
        for flag in flagged:
            claim = flag.get("claim", "")
            reason = flag.get("reason", "")
            severity = flag.get("severity", "MEDIUM")
            content.append(Paragraph(
                f"<b>• {claim}</b> [{severity}]: {reason}", body_style
            ))
        content.append(Spacer(1, 6))

    # Sources
    sources = memo_data.get("sources", {})
    sec = sources.get("sec_filings", [])
    news = sources.get("news_articles", [])

    content.append(Paragraph("Data Sources", section_style))
    content.append(HRFlowable(width="100%", thickness=0.5,
                               color=colors.HexColor("#cccccc")))
    content.append(Spacer(1, 4))
    if sec:
        content.append(Paragraph(
            f"<b>SEC Filings:</b> {', '.join(sec)}", body_style
        ))
    if news:
        content.append(Paragraph(
            f"<b>News Articles:</b> {len(news)} articles analyzed", body_style
        ))

    # Footer
    content.append(Spacer(1, 12))
    content.append(HRFlowable(width="100%", thickness=0.5,
                               color=colors.HexColor("#cccccc")))
    content.append(Paragraph(
        "This memo was generated by FinSight AI using SEC EDGAR data and news sources. "
        "This is not financial advice. Always consult a licensed financial advisor.",
        small_style
    ))

    # ── Build PDF ─────────────────────────────────────────────────────────────
    doc.build(content)
    print(f"   ✅ PDF generated: {filepath}")
    return str(filepath)


if __name__ == "__main__":
    print("Testing PDF Generator...\n")

    test_memo = {
        "ticker": "AAPL",
        "company_name": "Apple Inc.",
        "recommendation": "HOLD",
        "confidence_score": 0.80,
        "summary": (
            "Apple Inc. reported revenue of $416 billion for FY2025 | "
            "Net income of $112 billion with EPS of $7.49 | "
            "Strong business performance but no clear near-term catalyst"
        ),
        "bull_case": (
            "Strong revenue of $416B for FY2025 | "
            "High net income of $112B | "
            "Stable EPS of $7.49 indicating solid profitability"
        ),
        "bear_case": (
            "No clear near-term catalyst per KeyBanc analyst | "
            "Potential stock volatility | "
            "Intense competition in tech industry"
        ),
        "metrics": {
            "revenue": "$416,161,000,000 (FY2025)",
            "eps": "$7.49",
            "revenue_growth_yoy": None,
            "gross_margin": None,
            "guidance": None,
            "free_cash_flow": None,
        },
        "flagged_claims": [
            {
                "claim": "no clear catalyst to push stock higher",
                "reason": "based on analyst opinion, not concrete data",
                "severity": "LOW"
            },
            {
                "claim": "intense competition in tech industry",
                "reason": "not mentioned in provided source data",
                "severity": "MEDIUM"
            }
        ],
        "sources": {
            "sec_filings": ["SEC XBRL Company Facts", "10-Q (2026-01-30)", "10-K (2025-10-31)"],
            "news_articles": ["KeyBanc neutral rating", "Apple Studio Display review"],
            "filing_dates": ["2026-01-30", "2025-10-31"]
        }
    }

    pdf_path = generate_memo_pdf(test_memo)
    print(f"\nPDF saved to: {pdf_path}")
    print("\n✅ PDF Generator working correctly!")